/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface PrxAudioQuote {
        "src": string;
        "transcriptUrl": string;
    }
    interface PrxBgAurora {
        /**
          * Controls the height intensity of the aurora effect.
          * @default 1.0
         */
        "amplitude": number;
        /**
          * Controls the blending of the aurora effect with the background.
          * @default 0.5
         */
        "blend": number;
        /**
          * An array of three hex colors defining the aurora gradient.
          * @default ['#5227FF', '#7cff67', '#5227FF']
         */
        "colorStops": string[];
        /**
          * Controls the animation speed. Higher values make the aurora move faster.
          * @default 1.0
         */
        "speed": number;
        /**
          * Current time of animation. Use to externally control animation progress.
         */
        "time": number;
    }
}
declare global {
    interface HTMLPrxAudioQuoteElement extends Components.PrxAudioQuote, HTMLStencilElement {
    }
    var HTMLPrxAudioQuoteElement: {
        prototype: HTMLPrxAudioQuoteElement;
        new (): HTMLPrxAudioQuoteElement;
    };
    interface HTMLPrxBgAuroraElement extends Components.PrxBgAurora, HTMLStencilElement {
    }
    var HTMLPrxBgAuroraElement: {
        prototype: HTMLPrxBgAuroraElement;
        new (): HTMLPrxBgAuroraElement;
    };
    interface HTMLElementTagNameMap {
        "prx-audio-quote": HTMLPrxAudioQuoteElement;
        "prx-bg-aurora": HTMLPrxBgAuroraElement;
    }
}
declare namespace LocalJSX {
    interface PrxAudioQuote {
        "src"?: string;
        "transcriptUrl"?: string;
    }
    interface PrxBgAurora {
        /**
          * Controls the height intensity of the aurora effect.
          * @default 1.0
         */
        "amplitude"?: number;
        /**
          * Controls the blending of the aurora effect with the background.
          * @default 0.5
         */
        "blend"?: number;
        /**
          * An array of three hex colors defining the aurora gradient.
          * @default ['#5227FF', '#7cff67', '#5227FF']
         */
        "colorStops"?: string[];
        /**
          * Controls the animation speed. Higher values make the aurora move faster.
          * @default 1.0
         */
        "speed"?: number;
        /**
          * Current time of animation. Use to externally control animation progress.
         */
        "time"?: number;
    }
    interface IntrinsicElements {
        "prx-audio-quote": PrxAudioQuote;
        "prx-bg-aurora": PrxBgAurora;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "prx-audio-quote": LocalJSX.PrxAudioQuote & JSXBase.HTMLAttributes<HTMLPrxAudioQuoteElement>;
            "prx-bg-aurora": LocalJSX.PrxBgAurora & JSXBase.HTMLAttributes<HTMLPrxBgAuroraElement>;
        }
    }
}
